#ifndef BINDLESS_TEXTURES_HLSL
#define BINDLESS_TEXTURES_HLSL

#include "Common.hlsl"

#define ENABLE_SAMPLED_TEXTURE_ACCESS(TYPE, TEMPLATE)                                       \
DECLARE_RESOURCE_ARRAY_TEMPLATED(TYPE, TEMPLATE, SAMPLED_IMG_SET, GLOBAL_SAMPLER_COUNT)     \
IMPLEMENT_HANDLE_GETTER(TYPE, TEMPLATE)

#define ENABLE_STORAGE_TEXTURE_ACCESS(TYPE, TEMPLATE)                   \
DECLARE_RESOURCE_ARRAY_TEMPLATED(TYPE, TEMPLATE, STORAGE_IMG_SET, 0)    \
IMPLEMENT_HANDLE_GETTER(TYPE, TEMPLATE)

#define ENABLE_ALL_SAMPLED_TEXTURE_ACCESSES(FORMAT)         \
ENABLE_SAMPLED_TEXTURE_ACCESS(Texture1D, FORMAT)            \
ENABLE_SAMPLED_TEXTURE_ACCESS(Texture2D, FORMAT)            \
ENABLE_SAMPLED_TEXTURE_ACCESS(Texture2DArray, FORMAT)       \
ENABLE_SAMPLED_TEXTURE_ACCESS(Texture3D, FORMAT)            \
ENABLE_SAMPLED_TEXTURE_ACCESS(TextureCube, FORMAT)          

#define ENABLE_ALL_STORAGE_TEXTURE_ACCESSES(FORMAT)         \
ENABLE_STORAGE_TEXTURE_ACCESS(RWTexture1D, FORMAT)          \
ENABLE_STORAGE_TEXTURE_ACCESS(RWTexture2D, FORMAT)          \
ENABLE_STORAGE_TEXTURE_ACCESS(RWTexture2DArray, FORMAT)     \
ENABLE_STORAGE_TEXTURE_ACCESS(RWTexture3D, FORMAT)            

#define ENABLE_ALL_TEXTURE_ACCESSES(FORMAT)             \
ENABLE_ALL_SAMPLED_TEXTURE_ACCESSES(FORMAT)             \
ENABLE_ALL_STORAGE_TEXTURE_ACCESSES(FORMAT)

ENABLE_ALL_TEXTURE_ACCESSES(float)
ENABLE_ALL_TEXTURE_ACCESSES(float2)
ENABLE_ALL_TEXTURE_ACCESSES(float3)
ENABLE_ALL_TEXTURE_ACCESSES(float4)

ENABLE_ALL_TEXTURE_ACCESSES(int)
ENABLE_ALL_TEXTURE_ACCESSES(int2)
ENABLE_ALL_TEXTURE_ACCESSES(int3)
ENABLE_ALL_TEXTURE_ACCESSES(int4)

ENABLE_ALL_TEXTURE_ACCESSES(uint)
ENABLE_ALL_TEXTURE_ACCESSES(uint2)
ENABLE_ALL_TEXTURE_ACCESSES(uint3)
ENABLE_ALL_TEXTURE_ACCESSES(uint4)

#endif